using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MurkysRustBoot.Classes
{
    public class RustItems
    {

        public static List<string> Categories()
        {
            var categoryList = new List<string>();
            foreach (var item in ToList())
            {
                if (!categoryList.Contains(item.Category))
                {
                    categoryList.Add(item.Category);
                }
            }
            return categoryList;
        }

        public static List<RustItem> ToList()
        {
            return new List<RustItem>
            {
                new RustItem { ID = -1461508848, Category = "Weapon", DisplayName = "Assault Rifle" },
                new RustItem { ID = 2115555558, Category = "Ammunition", DisplayName = "Handmade Shell" },
                new RustItem { ID = -533875561, Category = "Ammunition", DisplayName = "Pistol Bullet" },
                new RustItem { ID = 1621541165, Category = "Ammunition", DisplayName = "Incendiary Pistol Bullet" },
                new RustItem { ID = -422893115, Category = "Ammunition", DisplayName = "HV Pistol Ammo" },
                new RustItem { ID = 815896488, Category = "Ammunition", DisplayName = "5.56 Rifle Ammo" },
                new RustItem { ID = 805088543, Category = "Ammunition", DisplayName = "Explosive 5.56 Rifle Ammo" },
                new RustItem { ID = 449771810, Category = "Ammunition", DisplayName = "Incendiary 5.56 Rifle Ammo" },
                new RustItem { ID = 1152393492, Category = "Ammunition", DisplayName = "HV 5.56 Rifle Ammo" },
                new RustItem { ID = 1578894260, Category = "Ammunition", DisplayName = "Rocket" },
                new RustItem { ID = 1436532208, Category = "Ammunition", DisplayName = "Incendiary Rocket" },
                new RustItem { ID = 542276424, Category = "Ammunition", DisplayName = "High Velocity Rocket" },
                new RustItem { ID = 1594947829, Category = "Ammunition", DisplayName = "Smoke Rocket WIP!!!!" },
                new RustItem { ID = -1035059994, Category = "Ammunition", DisplayName = "12 Gauge Buckshot" },
                new RustItem { ID = 1819281075, Category = "Ammunition", DisplayName = "12 Gauge Slug" },
                new RustItem { ID = 1685058759, Category = "Medical", DisplayName = "Anti-Radiation Pills" },
                new RustItem { ID = 93029210, Category = "Food", DisplayName = "Apple" },
                new RustItem { ID = -1565095136, Category = "Food", DisplayName = "Rotten Apple" },
                new RustItem { ID = -1280058093, Category = "Ammunition", DisplayName = "High Velocity Arrow" },
                new RustItem { ID = -420273765, Category = "Ammunition", DisplayName = "Wooden Arrow" },
                new RustItem { ID = 563023711, Category = "Traps", DisplayName = "Auto Turret" },
                new RustItem { ID = 790921853, Category = "Tool", DisplayName = "Salvaged Axe" },
                new RustItem { ID = -337261910, Category = "Medical", DisplayName = "Bandage" },
                new RustItem { ID = 498312426, Category = "Construction", DisplayName = "Concrete Barricade" },
                new RustItem { ID = 504904386, Category = "Construction", DisplayName = "Metal Barricade" },
                new RustItem { ID = -1221200300, Category = "Construction", DisplayName = "Sandbag Barricade" },
                new RustItem { ID = 510887968, Category = "Construction", DisplayName = "Stone Barricade" },
                new RustItem { ID = -814689390, Category = "Construction", DisplayName = "Wooden Barricade" },
                new RustItem { ID = 1024486167, Category = "Construction", DisplayName = "Barbed Wooden Barricade" },
                new RustItem { ID = 2021568998, Category = "Resources", DisplayName = "Battery - Small" },
                new RustItem { ID = 1046072789, Category = "Traps", DisplayName = "Snap Trap" },
                new RustItem { ID = 97409, Category = "Items", DisplayName = "Bed" },
                new RustItem { ID = 1611480185, Category = "Food", DisplayName = "Black Raspberries" },
                new RustItem { ID = 93832698, Category = "Medical", DisplayName = "Blood" },
                new RustItem { ID = -1063412582, Category = "Food", DisplayName = "Blueberries" },
                new RustItem { ID = 1624763669, Category = "Misc", DisplayName = "Blueprint Book" },
                new RustItem { ID = 1351589500, Category = "Misc", DisplayName = "Blueprint Fragment" },
                new RustItem { ID = -845335793, Category = "Misc", DisplayName = "Blueprint Library" },
                new RustItem { ID = 1625167035, Category = "Misc", DisplayName = "Blueprint Page" },
                new RustItem { ID = -55660037, Category = "Weapon", DisplayName = "Bolt Action Rifle" },
                new RustItem { ID = 1186854727, Category = "Attire", DisplayName = "Bone Jacket" },
                new RustItem { ID = 459479619, Category = "Attire", DisplayName = "Bone Armor Pants" },
                new RustItem { ID = 919780768, Category = "Weapon", DisplayName = "Bone Club" },
                new RustItem { ID = -365801095, Category = "Resources", DisplayName = "Bone Fragments" },
                new RustItem { ID = 68998734, Category = "Items", DisplayName = "Bota Bag" },
                new RustItem { ID = -853695669, Category = "Weapon", DisplayName = "Hunting Bow" },
                new RustItem { ID = 271534758, Category = "Items", DisplayName = "Large Wood Box" },
                new RustItem { ID = -770311783, Category = "Items", DisplayName = "Wood Storage Box" },
                new RustItem { ID = 1260209393, Category = "Attire", DisplayName = "Bucket Helmet" },
                new RustItem { ID = -307490664, Category = "Construction", DisplayName = "Building Plan" },
                new RustItem { ID = 115739308, Category = "Attire", DisplayName = "Leather Gloves" },
                new RustItem { ID = -1035315940, Category = "Attire", DisplayName = "Burlap Headwrap" },
                new RustItem { ID = 707427396, Category = "Attire", DisplayName = "Burlap Shirt" },
                new RustItem { ID = 707432758, Category = "Attire", DisplayName = "Burlap Shoes" },
                new RustItem { ID = 1767561705, Category = "Attire", DisplayName = "Burlap Trousers" },
                new RustItem { ID = -1342405573, Category = "Tool", DisplayName = "Camera" },
                new RustItem { ID = -139769801, Category = "Items", DisplayName = "Camp Fire" },
                new RustItem { ID = -1043746011, Category = "Food", DisplayName = "Can of Beans" },
                new RustItem { ID = 2080339268, Category = "Resources", DisplayName = "Empty Can Of Beans" },
                new RustItem { ID = -171664558, Category = "Food", DisplayName = "Can of Tuna" },
                new RustItem { ID = 1050986417, Category = "Resources", DisplayName = "Empty Tuna Can" },
                new RustItem { ID = 523409530, Category = "Food", DisplayName = "Candy Cane" },
                new RustItem { ID = 1300054961, Category = "Resources", DisplayName = "CCTV Camera" },
                new RustItem { ID = -2095387015, Category = "Items", DisplayName = "Ceiling Light" },
                new RustItem { ID = 1436001773, Category = "Resources", DisplayName = "Charcoal" },
                new RustItem { ID = 1711323399, Category = "Food", DisplayName = "Burned Chicken" },
                new RustItem { ID = 1734319168, Category = "Food", DisplayName = "Cooked Chicken." },
                new RustItem { ID = -1658459025, Category = "Food", DisplayName = "Raw Chicken Breast" },
                new RustItem { ID = -726947205, Category = "Food", DisplayName = "Spoiled Chicken" },
                new RustItem { ID = -341443994, Category = "Food", DisplayName = "Chocolate Bar" },
                new RustItem { ID = 94756378, Category = "Resources", DisplayName = "Cloth" },
                new RustItem { ID = 3059095, Category = "Resources", DisplayName = "Coal :(" },
                new RustItem { ID = -2128719593, Category = "Attire", DisplayName = "Coffee Can Helmet" },
                new RustItem { ID = 3059624, Category = "Food", DisplayName = "Corn" },
                new RustItem { ID = 583366917, Category = "Food", DisplayName = "Corn Seed" },
                new RustItem { ID = 2123300234, Category = "Weapon", DisplayName = "Crossbow" },
                new RustItem { ID = 1983936587, Category = "Resources", DisplayName = "Crude Oil" },
                new RustItem { ID = 1257201758, Category = "Construction", DisplayName = "Tool Cupboard" },
                new RustItem { ID = -1598790097, Category = "Construction", DisplayName = "Sheet Metal Double Door" },
                new RustItem { ID = -933236257, Category = "Construction", DisplayName = "Armored Double Door" },
                new RustItem { ID = -1575287163, Category = "Construction", DisplayName = "Wood Double Door" },
                new RustItem { ID = -2104481870, Category = "Construction", DisplayName = "Sheet Metal Door" },
                new RustItem { ID = -1571725662, Category = "Construction", DisplayName = "Armored Door" },
                new RustItem { ID = 1456441506, Category = "Construction", DisplayName = "Wooden Door" },
                new RustItem { ID = 1200628767, Category = "Misc", DisplayName = "Door Key" },
                new RustItem { ID = 498591726, Category = "Tool", DisplayName = "Timed Explosive Charge" },
                new RustItem { ID = 1755466030, Category = "Resources", DisplayName = "Explosives" },
                new RustItem { ID = -1034048911, Category = "Resources", DisplayName = "Animal Fat" },
                new RustItem { ID = 97513422, Category = "Tool", DisplayName = "Flare" },
                new RustItem { ID = 1229879204, Category = "Weapon", DisplayName = "Weapon Flashlight" },
                new RustItem { ID = -1722829188, Category = "Construction", DisplayName = "A floor grill" },
                new RustItem { ID = 1849912854, Category = "Construction", DisplayName = "Ladder Hatch" },
                new RustItem { ID = 28178745, Category = "Resources", DisplayName = "Low Grade Fuel" },
                new RustItem { ID = -505639592, Category = "Items", DisplayName = "Furnace" },
                new RustItem { ID = 1598149413, Category = "Items", DisplayName = "Large Furnace" },
                new RustItem { ID = -1779401418, Category = "Construction", DisplayName = "High External Stone Gate" },
                new RustItem { ID = -57285700, Category = "Construction", DisplayName = "High External Wooden Gate" },
                new RustItem { ID = 277631078, Category = "Construction", DisplayName = "Wind Turbine" },
                new RustItem { ID = 718197703, Category = "Food", DisplayName = "Granola Bar" },
                new RustItem { ID = 384204160, Category = "Weapon", DisplayName = "Beancan Grenade" },
                new RustItem { ID = -1308622549, Category = "Weapon", DisplayName = "F1 Grenade" },
                new RustItem { ID = -217113639, Category = "Misc", DisplayName = "Acoustic Guitar" },
                new RustItem { ID = -1580059655, Category = "Resources", DisplayName = "Gun Powder" },
                new RustItem { ID = -1224598842, Category = "Tool", DisplayName = "Hammer" },
                new RustItem { ID = -1976561211, Category = "Tool", DisplayName = "Salvaged Hammer" },
                new RustItem { ID = -1406876421, Category = "Attire", DisplayName = "Beenie Hat" },
                new RustItem { ID = -1397343301, Category = "Attire", DisplayName = "Boonie Hat" },
                new RustItem { ID = -1381682752, Category = "Attire", DisplayName = "Candle Hat" },
                new RustItem { ID = 696727039, Category = "Attire", DisplayName = "Baseball Cap" },
                new RustItem { ID = -450738836, Category = "Attire", DisplayName = "Miners Hat" },
                new RustItem { ID = 698310895, Category = "Tool", DisplayName = "Hatchet" },
                new RustItem { ID = -1078788046, Category = "Attire", DisplayName = "Hazmat Boots" },
                new RustItem { ID = 1057685737, Category = "Attire", DisplayName = "Hazmat Gloves" },
                new RustItem { ID = 1079752220, Category = "Attire", DisplayName = "Hazmat Helmet" },
                new RustItem { ID = 1133046397, Category = "Attire", DisplayName = "Hazmat Jacket" },
                new RustItem { ID = -1066276787, Category = "Attire", DisplayName = "Hazmat Pants" },
                new RustItem { ID = -148163128, Category = "Attire", DisplayName = "Hide Boots" },
                new RustItem { ID = -135651869, Category = "Attire", DisplayName = "Hide Pants" },
                new RustItem { ID = 102672084, Category = "Attire", DisplayName = "Hide Poncho" },
                new RustItem { ID = -1666761111, Category = "Attire", DisplayName = "Hide Vest" },
                new RustItem { ID = -465236267, Category = "Weapon", DisplayName = "Holosight" },
                new RustItem { ID = -1211618504, Category = "Attire", DisplayName = "Hoodie" },
                new RustItem { ID = 2133577942, Category = "Resources", DisplayName = "High Quality Metal Ore" },
                new RustItem { ID = -1014825244, Category = "Food", DisplayName = "Burned Human Meat" },
                new RustItem { ID = -991829475, Category = "Food", DisplayName = "Cooked Human Meat" },
                new RustItem { ID = -642008142, Category = "Food", DisplayName = "Raw Human Meat" },
                new RustItem { ID = 661790782, Category = "Food", DisplayName = "Spoiled Human Meat" },
                new RustItem { ID = -1440143841, Category = "Tool", DisplayName = "Salvaged Icepick" },
                new RustItem { ID = -1616887133, Category = "Attire", DisplayName = "Snow Jacket - Red" },
                new RustItem { ID = -1167640370, Category = "Attire", DisplayName = "Jacket" },
                new RustItem { ID = -1284735799, Category = "Items", DisplayName = "Jack O Lantern Angry" },
                new RustItem { ID = -1278649848, Category = "Items", DisplayName = "Jack O Lantern Happy" },
                new RustItem { ID = 776005741, Category = "Weapon", DisplayName = "Bone Knife" },
                new RustItem { ID = 108061910, Category = "Construction", DisplayName = "Wooden Ladder" },
                new RustItem { ID = 255101535, Category = "Traps", DisplayName = "Land Mine" },
                new RustItem { ID = -51678842, Category = "Items", DisplayName = "Lantern" },
                new RustItem { ID = -789202811, Category = "Medical", DisplayName = "Large Medkit" },
                new RustItem { ID = 516382256, Category = "Weapon", DisplayName = "Weapon Lasersight" },
                new RustItem { ID = 50834473, Category = "Resources", DisplayName = "Leather" },
                new RustItem { ID = -975723312, Category = "Construction", DisplayName = "Code Lock" },
                new RustItem { ID = 1908195100, Category = "Construction", DisplayName = "Lock" },
                new RustItem { ID = 146685185, Category = "Weapon", DisplayName = "Longsword" },
                new RustItem { ID = 193190034, Category = "Weapon", DisplayName = "M249" },
                new RustItem { ID = 3343606, Category = "Weapon", DisplayName = "Mace" },
                new RustItem { ID = 825308669, Category = "Weapon", DisplayName = "Machete" },
                new RustItem { ID = 107868, Category = "Items", DisplayName = "Paper Map" },
                new RustItem { ID = 997973965, Category = "Attire", DisplayName = "Improvised Balaclava" },
                new RustItem { ID = -46188931, Category = "Attire", DisplayName = "Bandana Mask" },
                new RustItem { ID = -2066726403, Category = "Food", DisplayName = "Burnt Bear Meat" },
                new RustItem { ID = -2043730634, Category = "Food", DisplayName = "Bear Meat Cooked" },
                new RustItem { ID = 1325935999, Category = "Food", DisplayName = "Bear Meat" },
                new RustItem { ID = 968732481, Category = "Food", DisplayName = "Burned Pork" },
                new RustItem { ID = 991728250, Category = "Food", DisplayName = "Cooked Pork" },
                new RustItem { ID = -253819519, Category = "Food", DisplayName = "Pork" },
                new RustItem { ID = -1714986849, Category = "Food", DisplayName = "Burned Wolf Meat" },
                new RustItem { ID = -1691991080, Category = "Food", DisplayName = "Cooked Wolf Meat" },
                new RustItem { ID = 179448791, Category = "Food", DisplayName = "Raw Wolf Meat" },
                new RustItem { ID = 431617507, Category = "Food", DisplayName = "Spoiled Wolf Meat" },
                new RustItem { ID = -46848560, Category = "Attire", DisplayName = "Metal Facemask" },
                new RustItem { ID = 688032252, Category = "Resources", DisplayName = "Metal Fragments" },
                new RustItem { ID = -1059362949, Category = "Resources", DisplayName = "Metal Ore" },
                new RustItem { ID = 1265861812, Category = "Attire", DisplayName = "Metal Chest Plate" },
                new RustItem { ID = 374890416, Category = "Resources", DisplayName = "High Quality Metal" },
                new RustItem { ID = -758925787, Category = "Construction", DisplayName = "Pump Jack" },
                new RustItem { ID = -1411620422, Category = "Construction", DisplayName = "Mining Quarry" },
                new RustItem { ID = 843418712, Category = "Food", DisplayName = "Mushroom" },
                new RustItem { ID = 3387378, Category = "Misc", DisplayName = "Note" },
                new RustItem { ID = 106433500, Category = "Attire", DisplayName = "Pants" },
                new RustItem { ID = 106434956, Category = "Resources", DisplayName = "Paper" },
                new RustItem { ID = -578028723, Category = "Tool", DisplayName = "Pick Axe" },
                new RustItem { ID = -1379225193, Category = "Weapon", DisplayName = "Eoka Pistol" },
                new RustItem { ID = -930579334, Category = "Weapon", DisplayName = "Revolver" },
                new RustItem { ID = 548699316, Category = "Weapon", DisplayName = "Semi-Automatic Pistol" },
                new RustItem { ID = 640562379, Category = "Items", DisplayName = "Pookie Bear" },
                new RustItem { ID = -1732316031, Category = "Misc", DisplayName = "Large Present" },
                new RustItem { ID = -2130280721, Category = "Misc", DisplayName = "Medium Present" },
                new RustItem { ID = -1725510067, Category = "Misc", DisplayName = "Small Present" },
                new RustItem { ID = -225085592, Category = "Food", DisplayName = "Pumpkin" },
                new RustItem { ID = 466113771, Category = "Food", DisplayName = "Pumpkin Seed" },
                new RustItem { ID = 2069925558, Category = "Items", DisplayName = "Reactive Target" },
                new RustItem { ID = -1026117678, Category = "Items", DisplayName = "Repair Bench" },
                new RustItem { ID = 1987447227, Category = "Items", DisplayName = "Research Table" },
                new RustItem { ID = 340009023, Category = "Attire", DisplayName = "Riot Helmet" },
                new RustItem { ID = -288010497, Category = "Attire", DisplayName = "Road Sign Jacket" },
                new RustItem { ID = -1595790889, Category = "Attire", DisplayName = "Road Sign Kilt" },
                new RustItem { ID = 3506021, Category = "Tool", DisplayName = "Rock" },
                new RustItem { ID = 649603450, Category = "Weapon", DisplayName = "Rocket Launcher" },
                new RustItem { ID = 192371071, Category = "Resources", DisplayName = "Salt Water" },
                new RustItem { ID = -1775234707, Category = "Weapon", DisplayName = "Salvaged Cleaver" },
                new RustItem { ID = -388967316, Category = "Weapon", DisplayName = "Salvaged Sword" },
                new RustItem { ID = 2007564590, Category = "Attire", DisplayName = "Santa Hat" },
                new RustItem { ID = -141135377, Category = "Weapon", DisplayName = "4x Zoom Scope" },
                new RustItem { ID = -1745053053, Category = "Weapon", DisplayName = "Semi-Automatic Rifle" },
                new RustItem { ID = 2057749608, Category = "Items", DisplayName = "Salvaged Shelves" },
                new RustItem { ID = 2107229499, Category = "Attire", DisplayName = "Boots" },
                new RustItem { ID = -1009492144, Category = "Weapon", DisplayName = "Pump Shotgun" },
                new RustItem { ID = 2077983581, Category = "Weapon", DisplayName = "Waterpipe Shotgun" },
                new RustItem { ID = -529054135, Category = "Construction", DisplayName = "Metal horizontal embrasure" },
                new RustItem { ID = -529054134, Category = "Construction", DisplayName = "Metal Vertical embrasure" },
                new RustItem { ID = 486166145, Category = "Construction", DisplayName = "Wood Shutters" },
                new RustItem { ID = 1628490888, Category = "Items", DisplayName = "Large Banner Hanging" },
                new RustItem { ID = 1498516223, Category = "Items", DisplayName = "Two Sided Hanging Sign" },
                new RustItem { ID = -632459882, Category = "Items", DisplayName = "Two Sided Ornate Hanging Sign" },
                new RustItem { ID = -626812403, Category = "Items", DisplayName = "Landscape Picture Frame" },
                new RustItem { ID = 385802761, Category = "Items", DisplayName = "Portrait Picture Frame" },
                new RustItem { ID = 2117976603, Category = "Items", DisplayName = "Tall Picture Frame" },
                new RustItem { ID = 1338515426, Category = "Items", DisplayName = "XL Picture Frame" },
                new RustItem { ID = -1455694274, Category = "Items", DisplayName = "XXL Picture Frame" },
                new RustItem { ID = 1579245182, Category = "Items", DisplayName = "Large Banner on pole" },
                new RustItem { ID = -587434450, Category = "Items", DisplayName = "Double Sign Post" },
                new RustItem { ID = -163742043, Category = "Items", DisplayName = "Single Sign Post" },
                new RustItem { ID = -1224714193, Category = "Items", DisplayName = "One Sided Town Sign Post" },
                new RustItem { ID = 644359987, Category = "Items", DisplayName = "Two Sided Town Sign Post" },
                new RustItem { ID = -1962514734, Category = "Items", DisplayName = "Huge Wooden Sign" },
                new RustItem { ID = -705305612, Category = "Items", DisplayName = "Large Wooden Sign" },
                new RustItem { ID = -357728804, Category = "Items", DisplayName = "Wooden Sign" },
                new RustItem { ID = -698499648, Category = "Items", DisplayName = "Small Wooden Sign" },
                new RustItem { ID = 1213686767, Category = "Weapon", DisplayName = "Silencer" },
                new RustItem { ID = 960793436, Category = "Resources", DisplayName = "Human Skull" },
                new RustItem { ID = 1001265731, Category = "Resources", DisplayName = "Wolf Skull" },
                new RustItem { ID = 1253290621, Category = "Items", DisplayName = "Sleeping Bag" },
                new RustItem { ID = 470729623, Category = "Items", DisplayName = "Small Oil Refinery" },
                new RustItem { ID = 1051155022, Category = "Items", DisplayName = "Small Stash" },
                new RustItem { ID = 927253046, Category = "Food", DisplayName = "Small Water Bottle" },
                new RustItem { ID = 109552593, Category = "Weapon", DisplayName = "Custom SMG" },
                new RustItem { ID = -2118132208, Category = "Weapon", DisplayName = "Stone Spear" },
                new RustItem { ID = -1127699509, Category = "Weapon", DisplayName = "Wooden Spear" },
                new RustItem { ID = -685265909, Category = "Traps", DisplayName = "Wooden Floor Spikes" },
                new RustItem { ID = -1623330855, Category = "Items", DisplayName = "SUPER Stocking" },
                new RustItem { ID = -1616524891, Category = "Items", DisplayName = "Small Stocking" },
                new RustItem { ID = 789892804, Category = "Tool", DisplayName = "Stone Pick Axe" },
                new RustItem { ID = -1289478934, Category = "Tool", DisplayName = "Stone Hatchet" },
                new RustItem { ID = -892070738, Category = "Resources", DisplayName = "Stones" },
                new RustItem { ID = -891243783, Category = "Resources", DisplayName = "Sulfur" },
                new RustItem { ID = 889398893, Category = "Resources", DisplayName = "Sulfur Ore" },
                new RustItem { ID = -1625468793, Category = "Tool", DisplayName = "Supply Signal" },
                new RustItem { ID = 1293049486, Category = "Tool", DisplayName = "Survey Charge" },
                new RustItem { ID = 586484018, Category = "Medical", DisplayName = "Medical Syringe" },
                new RustItem { ID = 1490499512, Category = "Resources", DisplayName = "Targeting Computer" },
                new RustItem { ID = 456448245, Category = "Weapon", DisplayName = "Thompson" },
                new RustItem { ID = 110547964, Category = "Tool", DisplayName = "Torch" },
                new RustItem { ID = -864578046, Category = "Attire", DisplayName = "T-Shirt" },
                new RustItem { ID = 1660607208, Category = "Attire", DisplayName = "Longsleeve T-Shirt" },
                new RustItem { ID = -496055048, Category = "Construction", DisplayName = "High External Stone Wall" },
                new RustItem { ID = -1792066367, Category = "Construction", DisplayName = "High External Wooden Wall" },
                new RustItem { ID = 562888306, Category = "Construction", DisplayName = "Prison Cell Gate" },
                new RustItem { ID = -427925529, Category = "Construction", DisplayName = "Prison Cell Wall" },
                new RustItem { ID = 995306285, Category = "Construction", DisplayName = "Chainlink Fence Gate" },
                new RustItem { ID = -378017204, Category = "Construction", DisplayName = "Chainlink Fence" },
                new RustItem { ID = 1175970190, Category = "Construction", DisplayName = "Shop Front" },
                new RustItem { ID = -1021702157, Category = "Construction", DisplayName = "Metal Window Bars" },
                new RustItem { ID = -402507101, Category = "Construction", DisplayName = "Reinforced Window Bars" },
                new RustItem { ID = -1556671423, Category = "Construction", DisplayName = "Wooden Window Bars" },
                new RustItem { ID = 112903447, Category = "Resources", DisplayName = "Water" },
                new RustItem { ID = 1817873886, Category = "Construction", DisplayName = "Large Water Catcher" },
                new RustItem { ID = 1824679850, Category = "Construction", DisplayName = "Small Water Catcher" },
                new RustItem { ID = 124310981, Category = "Attire", DisplayName = "Wolf Headdress" },
                new RustItem { ID = 3655341, Category = "Resources", DisplayName = "Wood" },
                new RustItem { ID = 1554697726, Category = "Attire", DisplayName = "Wood Chestplate" },
                new RustItem { ID = -1883959124, Category = "Attire", DisplayName = "Wood Armor Pants" }
            };
        }
    }

    public class RustItem
    {
        public int ID { get; set; }
        public string Category { get; set; }
        public string DisplayName { get; set; }
        public int Amount { get; set; } = 1;
        public bool IsAllowed { get; set; } = true;
        public bool IsBP { get; set; } = false;
    }
}
